name: Deploy to Vultr Production

on:
  push:
    branches:
      - release/production

jobs:
  build-and-deploy:
    name: Build and Deploy to Vultr
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4

    - name: Deploy to Vultr
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VULTR_HOST }}
        username: ${{ secrets.VULTR_USERNAME }}
        key: ${{ secrets.VULTR_SSH_KEY }}
        script: |
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          cd /home/xxxx/src/base-app
          git pull
          yarn
          yarn db:migrate
          yarn build
          pm2 restart base-app
